const CUSTOMROLE_NAME_PREFIX = "customrole_name:";
const CUSTOMROLE_COLOR_PREFIX = "customrole_color:";
const CUSTOMROLE_MEMBERS_PREFIX = "customrole_members:";
const CUSTOMROLE_EMOJI_PREFIX = "customrole_emoji:";
const CUSTOMROLE_DELETE_PREFIX = "customrole_delete:";
const CUSTOMROLE_REMOVE_SELECT_PREFIX = "customrole_remove_select:";

module.exports = {
  CUSTOMROLE_NAME_PREFIX,
  CUSTOMROLE_COLOR_PREFIX,
  CUSTOMROLE_MEMBERS_PREFIX,
  CUSTOMROLE_EMOJI_PREFIX,
  CUSTOMROLE_DELETE_PREFIX,
  CUSTOMROLE_REMOVE_SELECT_PREFIX,
};
