server:
  port: 2333
  address: 0.0.0.0

logging:
  level:
    root: ERROR
  request:
    enabled: false

lavalink:
  server:
    password: "youshallnotpass"
    bufferDurationMs: 3000
    frameBufferDurationMs: 12000
    trackStuckThresholdMs: 20000
    playerUpdateInterval: 10
    sources:
      youtube: false
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.0"
      repository: "https://maven.lavalink.dev/releases"