server:
  port: 2333
  address: 0.0.0.0

logging:
  level:
    root: ERROR
  request:
    enabled: false

lavalink:
  server:
    password: "youshallnotpass"
    bufferDurationMs: 600
    frameBufferDurationMs: 8000
    trackStuckThresholdMs: 15000
    playerUpdateInterval: 5
    sources:
      youtube: false
  plugins:
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.8.1"
      repository: "https://maven.lavalink.dev/releases"

plugins:
  lavasrc:
    providers:
      - "spsearch:%QUERY%"
    sources:
      spotify: true
      applemusic: false
      deezer: false
    spotify:
      clientId: "${SPOTIFY_CLIENT_ID}"
      clientSecret: "${SPOTIFY_CLIENT_SECRET}"
      countryCode: "IT"